language: node_js
node_js:
  - "7"
install:
  - npm install -g codecov
  - npm install
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov