#%RAML 1.0
title: Users Services
version: 1
baseUri: http://localhost:3000/{version}
documentation:
  - title: Welcome
    content: An Node JS supercool REST API to administrate users
/users:
  description: Endpoint to manage users.
  post:
    description: Creates an user
    body:
      application/json:
        example:
          {
            "email": "william@ball.com",
            "password": "fidelio",
            "name": "William"
          }
    responses: 
      201: 
        body: 
          application/json:
            example:
              {
                "_id": "d456ee7d-6c27-4de0-8007-139ffe74ea2d",
                "email": "william@ball.com",
                "name": "William",
                "createdAt": "2019-12-30T00:00:00.000Z"
              }
      422:
        body:
          application/json:
            example:
              {
                "errors": [{
                  "message": "error message"
                }]
              }
  /{id}:
    get:
      description: Find user by id
      responses: 
        200:
          body: 
            application/json: 
              example: 
                {
                  "_id": "d456ee7d-6c27-4de0-8007-139ffe74ea2d",
                  "email": "william@ball.com",
                  "name": "William",
                  "createdAt": "2019-12-30T00:00:00.000Z"
                }
        404:
          body: 
            application/json: 
              example: 
                {
                  "errors": [{
                    "message": "user not found"
                  }]
                }
    put:
      description: Edit an user
      body:
        application/json:
          example:
            {
              "email": "new@email.com",
              "password": "new_password",
              "name": "New Name"
            }
      responses: 
        200:
          body: 
            application/json: 
              example: 
                {
                  "_id": "d456ee7d-6c27-4de0-8007-139ffe74ea2d",
                  "email": "new@email.com",
                  "name": "New Name",
                  "createdAt": "2019-12-30T00:00:00.000Z"
                }
    /password/valid:
      post:
        description: Check if the password is valid
        body:
          application/json:
            example:
              {
                "value": "fidelio"
              }
        responses: 
          200:
            body: 
              application/json: 
                example: 
                  {
                    "valid": true
                  }
